### PR TITLE
Adding QR slash command

### PR DESCRIPTION
**Pull request by gvarner13**
Opening this but I still need to figure out the deploy for the commands. The deploy_commands needs to run whenever the file is updated to deploy the new commands to Discord.

- [ ] Need to run the deploy_commands script when ever the file updates. (Needs node 16 to run it)

#68

### CODE REVIEW

**Comment by drobati** [comment]
Honestly, I don't know why I run tests against node 14. Everything runs on 16.

**Comment by gvarner13** [comment]
I'm going to try and make a workflow that runs after ci passes and only when the deploy file has changed.

**Comment by drobati** [comment]
How's this going?

**Comment by gvarner13** [comment]
@drobati Need to work with you on the deploy command.

**Comment by drobati** [comment]
Going to close this since all this has been implemented in latest PR merged.

**Pull request closed without merging**
